version: '3'

############### DOCKERS ##################
services:
  #### PHP SERVER ####
  app:
    container_name: app
    image: php-app:camagru
    build:
      context: requirements/php/
    env_file:
      - .env
    environment:
      - SESSION_MANAGER=${SESSION_MANAGER}
    networks:
      - camagru_network
    # volumes:
    #   - ./requirements/php/website:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - database
    restart: unless-stopped

  #### MYSQL DATABASE ####
  database:
    container_name: mysql
    image: camagru-database:camagru
    build:
      context: requirements/database/
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - camagru_network

  #### PHPMYADMIN ####
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: unless-stopped
    environment:
        PMA_HOST: mysql
    networks:
      - camagru_network
    depends_on:
      - database

############### NETWORKS ##################

networks:
  camagru_network: