version: '3'

############### DOCKERS ##################
services:
  #### PHP SERVER ####
  app:
    container_name: app
    image: php-app:camagru
    build:
      context: requirements/php/
    env_file:
      - .env
    networks:
      - camagru_network
    volumes:
      - ./requirements/php/website:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - database
    restart: unless-stopped

  #### POSTGRESQL DATABASE ####
  database:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - camagru_network
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - ./requirements/database/init/create-db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  #### ADMINER ####
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - '8080:8080'
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - camagru_network
    depends_on:
      - database

############### NETWORKS ##################

networks:
  camagru_network: